version: "3"
services:
  application:
    container_name: criapet-app
    build:
      args:
        user: ${SO_DOCKER_USER}
        uid: 1000
      context: ./docker-compose/application
    working_dir: /var/www
    volumes:
      - ./application:/var/www
    networks:
      - criapet-network

  mysql:
    container_name: criapet-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: criapet
    volumes:
      - mysqlvolume:/var/lib/mysql
    networks:
      - criapet-network
    ports:
      - "3306:3306"

  nginx:
    container_name: criapet-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./application:/var/www
      - ./docker-compose/nginx/conf/:/etc/nginx/conf.d/
    networks:
      - criapet-network

volumes:
  mysqlvolume:

networks:
  criapet-network:
    driver: bridge